### ISSUE TITLE
QComboBox type error when trying to run the plugin

### ISSUE THREAD

**Issue by ruffinevans** [ianmcb/beetime#1]
When I try to run the plugin through Anki, I encounter the following error:

> > > Traceback (most recent call last):
> > >   File "C:\Users\Ruffin\Documents\Anki\addons\beetime__init__.py", line 16, in openBeeminderSettings dialog.display(mw)
> > >   File "C:\Users\Ruffin\Documents\Anki\addons\beetime\settings.py", line 94, in display
> > > 
> > > TypeError: QComboBox.setCurrentIndex(int): argument 1 has unexpected type 'str'

Thanks for your work developing this plugin! I'm looking forward to using it.

**Comment by ianmcb** [comment]
~~Did this happen immediately after installing the add-on, changing settings or starting up Anki? Has it worked correctly before?~~

~~Could you open the console in Anki using Ctrl+: (colon) and paste `pp(mw.col.conf['beeconf'])`, Ctrl+Enter to execute and paste the results here? Before copy-pasting here, search for your username and API key in the output and please redact those out.~~

Nevermind, can reproduce. Will look into it! Thanks for your report.

**Comment by ianmcb** [comment]
Fixed, uploaded an updated version to AnkiWeb. Let me know how it goes.

**Comment by ruffinevans** [comment]
Works great now, thanks again
